name: biogemgt_task
channels:
  - anaconda
  - conda-forge
dependencies:
  - anyio=4.1.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.1
  - beautifulsoup4=4.12.2
  - biopython=1.81
  - blas=1.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.1.4
  - contourpy=1.2.0
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.46.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - idna=3.6
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - importlib_resources=6.1.1
  - ipykernel=6.26.0
  - ipython=8.18.1
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.12.1
  - jupyter_server_terminals=0.5.0
  - jupyterlab=4.0.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.12.0
  - nbconvert-core=7.12.0
  - nbconvert-pandoc=7.12.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.0
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.4
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - pooch=1.8.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.32.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.13.2
  - scikit-learn=1.2.0
  - scipy=1.10.1
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.14.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uri-template=1.3.0
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - bioseq==0.2.3
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/biogemgt_task
