name: biogemgt_task
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2023.11.17=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.44.2=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h463b476_2
  - openssl=3.2.0=h0d3ecfb_1
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.11.0=h3ba56d0_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2023c=h71feb2d_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - bioseq==0.2.3
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/biogemgt_task
